CREATE TABLE IF NOT EXISTS categories(
	id BIGSERIAL PRIMARY KEY,
  	name VARCHAR(200) UNIQUE NOT NULL
);


CREATE TABLE IF NOT EXISTS products (
	id VARCHAR(250) PRIMARY KEY,
  	name VARCHAR(200) NOT NULL,
  	price DECIMAL(8, 2) NOT NULL,
  	category_id INTEGER,
  	FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE
);